import { csvEscape, fmtDate, fmtMoney, fmtMoneyExact, toISODate } from "./format";
import type { AnalysisResult } from "./types";

export function downloadFile(name: string, content: string, type = "text/plain") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function buildOverdueCSV(result: AnalysisResult) {
  const head = ["Priority", "Invoice No", "Customer", "Outstanding", "Due Date", "Days Overdue", "Risk", "Suggested Action", "Email"];
  const lines = [head.join(",")];

  result.actionList.forEach((record) => {
    const action = !record.email
      ? "Find contact, then chase"
      : record.priorityRisk === "Critical"
        ? "Call + final notice"
        : record.priorityRisk === "High"
          ? "Firm reminder today"
          : "Friendly reminder";
    lines.push(
      [
        record.priority,
        record.invNo,
        record.customer,
        fmtMoneyExact(record.outstanding),
        fmtDate(record.due),
        record.daysOverdue,
        record.priorityRisk,
        action,
        record.email,
      ]
        .map(csvEscape)
        .join(","),
    );
  });

  return lines.join("\n");
}

export function buildIssuesCSV(result: AnalysisResult) {
  const head = ["Invoice No", "Customer", "Issues", "Severity"];
  const lines = [head.join(",")];

  result.records
    .filter((record) => record.issues.length)
    .forEach((record) => {
      lines.push([record.invNo, record.customer, record.issues.map((issue) => issue.t).join("; "), record.hasErr ? "Error" : "Warning"].map(csvEscape).join(","));
    });

  return lines.join("\n");
}

export function buildSummaryMarkdown(result: AnalysisResult) {
  const metrics = result.metrics;
  const stamp = result.asOf.toLocaleDateString("en-AU", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
  const top = result.actionList.slice(0, 5);
  const risky = result.customers.filter((customer) => customer.risk === "Critical" || customer.risk === "High").slice(0, 5);

  let markdown = `# Weekly Invoice Health Summary\n\n_As at ${stamp}_\n\n`;
  markdown += "## At a glance\n\n";
  markdown += `- **Total outstanding:** ${fmtMoney(metrics.totalOutstanding)} across ${metrics.active} open invoice${metrics.active !== 1 ? "s" : ""}\n`;
  markdown += `- **Overdue:** ${fmtMoney(metrics.totalOverdue)} across ${metrics.overdueCount} invoice${metrics.overdueCount !== 1 ? "s" : ""}\n`;
  markdown += `- **Average days overdue:** ${metrics.avgDaysOverdue}\n`;
  if (metrics.weightedAgeDays !== null) {
    markdown += `- **Weighted age of receivables:** ${metrics.weightedAgeDays} days\n`;
  }
  markdown += `- **High-priority follow-ups:** ${metrics.critCount}\n`;
  markdown += `- **Data quality issues found:** ${metrics.issuesCount}\n\n`;

  markdown += "## Receivables aging\n\n";
  markdown += "| Bucket | Invoices | Amount |\n|---|---:|---:|\n";
  result.aging.forEach((bucket) => {
    markdown += `| ${bucket.label} | ${bucket.count} | ${fmtMoney(bucket.amount)} |\n`;
  });
  markdown += "\n## Who to follow up first\n\n";

  top.forEach((record, index) => {
    markdown += `${index + 1}. **${record.customer}** - ${fmtMoney(record.outstanding)} (${record.invNo}), ${record.daysOverdue} days overdue. ${record.reasons.slice(0, 2).join(", ")}.\n`;
  });

  if (risky.length) {
    markdown += "\n## Customers to watch\n\n";
    risky.forEach((customer) => {
      markdown += `- **${customer.name}** - ${customer.risk} risk. ${fmtMoney(customer.outstanding)} outstanding${
        customer.avgDaysLate !== null ? `, historically pays ${customer.avgDaysLate} days late` : ""
      }.\n`;
    });
  }

  markdown += "\n---\n\n_Generated by InvoicePulse AU. This is a data quality and workflow summary only - not accounting, tax, legal, or debt-collection advice._\n";
  return markdown;
}

export function exportOverdueCSV(result: AnalysisResult) {
  const stamp = toISODate(result.asOf);
  downloadFile(`invoicepulse-overdue-${stamp}.csv`, buildOverdueCSV(result), "text/csv");
}

export function exportIssuesCSV(result: AnalysisResult) {
  const stamp = toISODate(result.asOf);
  downloadFile(`invoicepulse-data-issues-${stamp}.csv`, buildIssuesCSV(result), "text/csv");
}

export function exportSummaryMD(result: AnalysisResult) {
  const stamp = toISODate(result.asOf);
  downloadFile(`invoicepulse-weekly-summary-${stamp}.md`, buildSummaryMarkdown(result), "text/markdown");
}
